employees = [
    {"ID": 1, "Name": "Jack Sparrow", "Efficiency Rate": 82, "Customer Rating": 92, "IMED Information Ratio": 88, "Acceptance Rate": 98, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 2, "Name": "Elizabeth Swann", "Efficiency Rate": 87, "Customer Rating": 89, "IMED Information Ratio": 90, "Acceptance Rate": 96, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 3, "Name": "Tony Stark", "Efficiency Rate": 78, "Customer Rating": 85, "IMED Information Ratio": 70, "Acceptance Rate": 97, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 4, "Name": "Steve Rogers", "Efficiency Rate": 91, "Customer Rating": 93, "IMED Information Ratio": 95, "Acceptance Rate": 99, "mentor": True,"Employment Status": "Full-time"},
    {"ID": 5, "Name": "Natasha Romanoff", "Efficiency Rate": 84, "Customer Rating": 88, "IMED Information Ratio": 78, "Acceptance Rate": 95, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 6, "Name": "Thor Odinson", "Efficiency Rate": 80, "Customer Rating": 90, "IMED Information Ratio": 81, "Acceptance Rate": 98, "mentor": True,"Employment Status": "Full-time"},
    {"ID": 7, "Name": "Bruce Wayne", "Efficiency Rate": 76, "Customer Rating": 84, "IMED Information Ratio": 65, "Acceptance Rate": 94, "mentor": False,"Employment Status": "Part-time"},
    {"ID": 8, "Name": "Selina Kyle", "Efficiency Rate": 85, "Customer Rating": 91, "IMED Information Ratio": 88, "Acceptance Rate": 97, "mentor": False,"Employment Status": "Part-time"},
    {"ID": 9, "Name": "Clark Kent", "Efficiency Rate": 90, "Customer Rating": 95, "IMED Information Ratio": 92, "Acceptance Rate": 99, "mentor": True,"Employment Status": "Part-time"},
    {"ID": 10, "Name": "Diana Prince", "Efficiency Rate": 89, "Customer Rating": 87, "IMED Information Ratio": 85, "Acceptance Rate": 98, "mentor": False,"Employment Status": "Part-time"},
    {"ID": 11, "Name": "Peter Parker", "Efficiency Rate": 77, "Customer Rating": 80, "IMED Information Ratio": 75, "Acceptance Rate": 93, "mentor": False,"Employment Status": "Part-time"},
    {"ID": 12, "Name": "Wanda Maximoff", "Efficiency Rate": 82, "Customer Rating": 89, "IMED Information Ratio": 87, "Acceptance Rate": 96, "mentor": True,"Employment Status": "Part-time"},
    {"ID": 13, "Name": "Stephen Strange", "Efficiency Rate": 88, "Customer Rating": 92, "IMED Information Ratio": 90, "Acceptance Rate": 97, "mentor": False,"Employment Status": "Part-time"},
    {"ID": 14, "Name": "Arthur Curry", "Efficiency Rate": 80, "Customer Rating": 85, "IMED Information Ratio": 79, "Acceptance Rate": 95, "mentor": True,"Employment Status": "Part-time"},
    {"ID": 15, "Name": "Harley Quinn", "Efficiency Rate": 79, "Customer Rating": 83, "IMED Information Ratio": 72, "Acceptance Rate": 94, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 16, "Name": "Bruce Banner", "Efficiency Rate": 83, "Customer Rating": 86, "IMED Information Ratio": 80, "Acceptance Rate": 96, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 17, "Name": "Scott Lang", "Efficiency Rate": 84, "Customer Rating": 87, "IMED Information Ratio": 77, "Acceptance Rate": 95, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 18, "Name": "Carol Danvers", "Efficiency Rate": 90, "Customer Rating": 94, "IMED Information Ratio": 91, "Acceptance Rate": 98, "mentor": True,"Employment Status": "Full-time"},
    {"ID": 19, "Name": "Gamora Zen-Whoberi", "Efficiency Rate": 86, "Customer Rating": 88, "IMED Information Ratio": 86, "Acceptance Rate": 97, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 20, "Name": "Peter Quill", "Efficiency Rate": 79, "Customer Rating": 84, "IMED Information Ratio": 74, "Acceptance Rate": 94, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 21, "Name": "Loki Laufeyson", "Efficiency Rate": 83, "Customer Rating": 89, "IMED Information Ratio": 81, "Acceptance Rate": 95, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 22, "Name": "Pepper Potts", "Efficiency Rate": 88, "Customer Rating": 90, "IMED Information Ratio": 85, "Acceptance Rate": 97, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 23, "Name": "T'Challa", "Efficiency Rate": 87, "Customer Rating": 92, "IMED Information Ratio": 89, "Acceptance Rate": 96, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 24, "Name": "Shuri", "Efficiency Rate": 90, "Customer Rating": 94, "IMED Information Ratio": 93, "Acceptance Rate": 99, "mentor": True,"Employment Status": "Full-time"},
    {"ID": 25, "Name": "Bucky Barnes", "Efficiency Rate": 81, "Customer Rating": 87, "IMED Information Ratio": 80, "Acceptance Rate": 94, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 26, "Name": "Vision", "Efficiency Rate": 85, "Customer Rating": 91, "IMED Information Ratio": 86, "Acceptance Rate": 96, "mentor": True,"Employment Status": "Full-time"},
    {"ID": 27, "Name": "Clint Barton", "Efficiency Rate": 82, "Customer Rating": 88, "IMED Information Ratio": 83, "Acceptance Rate": 95, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 28, "Name": "Sam Wilson", "Efficiency Rate": 87, "Customer Rating": 89, "IMED Information Ratio": 88, "Acceptance Rate": 97, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 29, "Name": "Antonia Dreykov", "Efficiency Rate": 80, "Customer Rating": 83, "IMED Information Ratio": 76, "Acceptance Rate": 93, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 30, "Name": "Katherine Pryde", "Efficiency Rate": 79, "Customer Rating": 84, "IMED Information Ratio": 75, "Acceptance Rate": 92, "mentor": True,"Employment Status": "Full-time"},
    {"ID": 31, "Name": "Jean Grey", "Efficiency Rate": 86, "Customer Rating": 91, "IMED Information Ratio": 87, "Acceptance Rate": 95, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 32, "Name": "Rogue Anna", "Efficiency Rate": 81, "Customer Rating": 86, "IMED Information Ratio": 82, "Acceptance Rate": 94, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 33, "Name": "Charles Xavier", "Efficiency Rate": 89, "Customer Rating": 93, "IMED Information Ratio": 90, "Acceptance Rate": 98, "mentor": True,"Employment Status": "Full-time"},
    {"ID": 34, "Name": "Erik Lehnsherr", "Efficiency Rate": 82, "Customer Rating": 88, "IMED Information Ratio": 85, "Acceptance Rate": 96, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 35, "Name": "Storm Munroe", "Efficiency Rate": 84, "Customer Rating": 89, "IMED Information Ratio": 84, "Acceptance Rate": 97, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 36, "Name": "Logan Howlett", "Efficiency Rate": 80, "Customer Rating": 85, "IMED Information Ratio": 78, "Acceptance Rate": 94, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 37, "Name": "Remy LeBeau", "Efficiency Rate": 77, "Customer Rating": 83, "IMED Information Ratio": 74, "Acceptance Rate": 92, "mentor": True,"Employment Status": "Full-time"},
    {"ID": 38, "Name": "Jubilee Lee", "Efficiency Rate": 78, "Customer Rating": 84, "IMED Information Ratio": 73, "Acceptance Rate": 91, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 39, "Name": "Wade Wilson", "Efficiency Rate": 81, "Customer Rating": 87, "IMED Information Ratio": 81, "Acceptance Rate": 94, "mentor": False,"Employment Status": "Full-time"},
    {"ID": 40, "Name": "Vanessa Carlysle", "Efficiency Rate": 83, "Customer Rating": 89, "IMED Information Ratio": 86, "Acceptance Rate": 95, "mentor": False,"Employment Status":"Part-time"},
]